apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://grafana-community.github.io/helm-charts
      chart: grafana
      targetRevision: "13.2.5"
      helm:
        releaseName: grafana
        valueFiles:
          - $values/deploy/values/grafana.yaml
    - repoURL: https://github.com/szymon-grabowski/portfolio.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/szymon-grabowski/portfolio.git
      targetRevision: main
      path: deploy/dashboards
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 10
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
