dex:
  enabled: false
notifications:
  enabled: false
applicationSet:
  replicas: 0

configs:
  params:
    server.insecure: true   # UI only via port-forward
    controller.status.processors: 5
    controller.operation.processors: 3
    reposerver.parallelism.limit: 1
  cm:
    timeout.reconciliation: 180s
    admin.enabled: true

controller:
  resources:
    requests: { cpu: 50m, memory: 256Mi }
    limits: { memory: 384Mi }
repoServer:
  resources:
    requests: { cpu: 20m, memory: 128Mi }
    limits: { memory: 256Mi }
server:
  resources:
    requests: { cpu: 10m, memory: 64Mi }
    limits: { memory: 128Mi }
redis:
  resources:
    requests: { cpu: 10m, memory: 32Mi }
    limits: { memory: 64Mi }
redisSecretInit:
  resources:
    requests: { cpu: 10m, memory: 16Mi }
    limits: { memory: 64Mi }
