deploymentMode: SingleBinary

loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
  schemaConfig:
    configs:
      - from: "2026-01-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h
  limits_config:
    retention_period: 168h
    query_timeout: 30s
    max_query_series: 500
    max_entries_limit_per_query: 2000
    ingestion_rate_mb: 2
    ingestion_burst_size_mb: 4
  compactor:
    retention_enabled: true
    delete_request_store: filesystem

singleBinary:
  replicas: 1
  resources:
    requests: { cpu: 50m, memory: 128Mi }
    limits: { memory: 384Mi }
  persistence:
    size: 10Gi

chunksCache:
  enabled: false
resultsCache:
  enabled: false
gateway:
  enabled: false
lokiCanary:
  enabled: false
test:
  enabled: false
minio:
  enabled: false
read:
  replicas: 0
write:
  replicas: 0
backend:
  replicas: 0
sidecar:
  rules:
    enabled: false
