apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-discord
    namespace: monitoring
type: Opaque
data:
    webhook-url: ENC[AES256_GCM,data:BeeiD+canzCP8VstEOUrZd5B0xg4f6wFpHfOedwGxXElPlQs++NBtu8tJJ30RXUkxGd1mPaGw+myesess6/F5CvYESDFLrYanN/EEXQdcpU0A5IU1ZmNQT7v7WPQlXW/RCtDl/5CRSgaUL/fsbrff4rFv08vBxbFGLxCKGzcA4c3xhE/HK+RMhmaSpcMxiD9UXV2U/U9cSaGq/flC5abpC/mUsE=,iv:q6enEeESLBJ2TVrO6WJmSTMs5tjjq3AG/ogLQZGcg08=,tag:r4YonHd/u9i4Z36GxgQvSg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVeWpmT0lGdVI2UDZtUlJl
            RmxHWlYxVGh2anZtRkV5WjhaTmJubnVFSlJZClNSV0RGQjU3KzA0ZmU2ekdrbExv
            aS9uODRTQnFJaHlORnF3eUwyWFRzSzAKLS0tIFhDaktkSXg5UitVWm1uTGd1bnJl
            cmNIR0tITlhESjlzQjFScVdQVHBLem8K9O98KkC6Spjun/6zN/WpOPw1fyybqq8B
            vTMxbpLNknKKDukVxEa2CJTUBqzPc4cMZuBy0IMpD6W/JHXW2DEd9g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tjlp4e6yjzc0tu8tun8nsjh7nrhc9h8qtswrzxh6pk67axphh3fqgre4ve
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T13:22:36Z"
    mac: ENC[AES256_GCM,data:KleL9/yuljNHOfdUu7WSwGEkKVpDboWCFqZ8rD+qQm3ewCXbxu6bOpbvaMenxCz3JP8vZzy6GAcPzYX9alFo9Z0kagAac8XhZ3LhKR6V9DlUg42UKEcnF+tbobt0Rw7g41T+11lEjoRKBrksJBdQrvCLRd6pxbOrK9S8NYDU3RM=,iv:twHaXGbfRhEvaGLl2vsHYm8I8mMVlFf9LRd3LQpMU1k=,tag:Tr89NrcZJwU/6sSCeK2mDA==,type:str]
    version: 3.13.3
