apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-healthchecks
    namespace: monitoring
type: Opaque
data:
    ping-url: ENC[AES256_GCM,data:5dZJvASP9CZzHXkK4DzPQoeGNriqRRYdVgafjI4KjjCJG7x6s9t2Id/0KZcfI6w+z8uGnWG/bt4wcrP2w9UbwJxMZ0ZYIfHXXh53hw==,iv:3q9de5GOyGCi0MH7Kvvxt9MC5GUvnsyQZP0qnxpWfiM=,tag:0+0J80CMrJVQLZwEt/9fIg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJOUNHZXVJZFFzYWFuckpR
            UGhqZVNQci9CK2VPTHYzSkNDWWdaNlI3VWpjCmk5U0Zkc20yR2lvS3VGcVhVRmto
            WkFXQndlUnozYXRlUjdvL2NyUXd4TDAKLS0tIGtvZzh4OXBwakJVcVc1aHVPVHRP
            R0ZxT1pOdXdUOVkvYVVJVHM1VU9BYncKMnXV/06+HzCOmkeK7bK1zXlMpCprW/3G
            CeU3g7Gi4VO5rVnmRszsKBDNe5o+tLN28n58OiNrDsOiCBC56MjF7A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tjlp4e6yjzc0tu8tun8nsjh7nrhc9h8qtswrzxh6pk67axphh3fqgre4ve
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T13:22:36Z"
    mac: ENC[AES256_GCM,data:vv5yyJon1ZQtK+n5pYjI6k23A286vmpAZgMGZcy/x6Yk+NY9RR5xxV0TkZQwKQNjJOlMv7sJfOR39TEezsaH28GpGA1x7/7D3fd83gQWPdGAZUaTA8AKfxZW8YLxOy6xJuA8jzM8YjsQO5mATgrl94gEBD2FmWVQlGb9kMGoUVs=,iv:IZqHNWx0WM/hbTzlBlGUv1tjGDIlZMJnvKEQnDDkmcI=,tag:027bPZTlk9SLfZP8G9+wkA==,type:str]
    version: 3.13.3
