apiVersion: v1
kind: Secret
metadata:
    name: argocd-secret
    namespace: argocd
type: Opaque
data:
    admin.password: ENC[AES256_GCM,data:VHpUoHx8gp5sioOYJhojx5TfXNAP34sMkGjiShGiVNWNNDRJtL9xwGj5nyCJyuhWkb8t7X4dT11U7y9slCXHGZrosladM/C79Vkwn8tgPYk=,iv:7pECrum54p4/0LUyt3CTvs9IyVM+QmFXtkKAAF67/6I=,tag:BHuNKN9L10zHm0PXHWqD1w==,type:str]
    admin.passwordMtime: ENC[AES256_GCM,data:OZiZyV9SUP54fK/JqcAQOdJzRGlT8OnpP3LadQ==,iv:nm3ut6KC64RV2QHB0jUZHRvlYpXANNCPPrxRxC0dxTU=,tag:h2VqwOP4RtdxTD0ARQ7jtg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWSDNzYVVHT1FpY2k2TVV4
            RGprREhsTDFqTFUyajY0K3FWRzBmZXRScUgwCis4eUtwbUhQcmFaWjhvMzBGR0sv
            bDFucHpSdU5aUE5CZkVPeE9Lak5iWVEKLS0tIGxjMWtteTU3SjhPaWxMakpPUFIw
            dnhvaEZFczM3RE96L3dwYnNYTkd2dVEKP/upOZOdClFumsPwgw5TYZ6/JcxgdzLJ
            baB1Pl687O7y4bM5Y22LSmSKfXs9LkbfnTYVyniHqjRaFl2n8EwuKQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tjlp4e6yjzc0tu8tun8nsjh7nrhc9h8qtswrzxh6pk67axphh3fqgre4ve
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T13:22:37Z"
    mac: ENC[AES256_GCM,data:OQgywx3YpIb4LvnzlenXnwjRg4TgJCL5VFUCNzAYKwdjZWm+Uwx/5BGoX0GxATR41i3o92S0b5oFaPVxl5SUz1jM4MLaQ0zf61KVy/KNWKddNMKZuNb+jhQjfL4bkj5G9ieF2WYcuhxWvpEPP5exBELqtHyecHJCWx9DHSZhZfU=,iv:4bp2r/bGWg9vUsPNdoAt+dwZS9rnviiuHn9m9Pxfk0Y=,tag:CT/0A82/z0Kxcg6m44dAVQ==,type:str]
    version: 3.13.3
