apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
data:
    admin-password: ENC[AES256_GCM,data:j0e32rE0rAoEPYe1y4cWJ0pgZEHmFCueycaLX5vkWWTGfH+bF7PXhY3rFR0=,iv:RGQVlHDXtBITj9a24MNGiVpsfY0Eqi1X3oS+nBsU8ZU=,tag:dziEUU3Ykci1LVqpeFj1MA==,type:str]
    admin-user: ENC[AES256_GCM,data:YpGS9Z08u3M=,iv:rQO42XCuBiVncc0RykTKNuXsD2n6C8IhIsZBUQs/Z3Y=,tag:LogyqLokIiDVvUGWE4aR5g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRYkJKMlhoY1lxMVp6M05u
            dDdwVVk4NHZDNUFnSkFHSVZFRGE4U01UQ1ZJCm1Sek5VdDdTWGR4Q09ZOCs2THZs
            bHFWRk5YOWR0MDlIQStvVEhUL0xIOGsKLS0tIEtQTVJWN0pXck80MXlkMWUwK2Rz
            YTI1QmVBSWZtcUtLL0hOdmIzaCtBeFUKXheO2MPOlBBG9BIEIrajaCNEJJ7hfqVp
            9jR6D15B+9ST38NLeuqGiUjx+c3xHxKrBRG5nFOPP2yX0gGmGIno3A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tjlp4e6yjzc0tu8tun8nsjh7nrhc9h8qtswrzxh6pk67axphh3fqgre4ve
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T13:22:36Z"
    mac: ENC[AES256_GCM,data:nQG3n37gfNzbv0HWQnpnax8xvxSJiNyweJfOi9gJLWoy7dxSmKc4UHUoezVfvckrKGh1J657T7/bHkkeHaUT0wJE4UH3RXcSDkZY0mjQ+FY/457+MyiQs/ykUzU5e6qht2Yvtq4JrvmYVnKvT/odLxy3qNINmAv41zqAh2Hg2Ic=,iv:8Jaapbf5s6JTTbWTNqRGqIUM5ppJL+3vyuImI/5YuGs=,tag:rXIePASNobu/88uEzY/coQ==,type:str]
    version: 3.13.3
