{{- if .Values.ingress.hsts }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: hsts
  labels:
    {{- include "portfolio.labels" . | nindent 4 }}
spec:
  headers:
    stsSeconds: 31536000
    stsIncludeSubdomains: true
{{- end }}
{{- if .Values.ingress.redirectWww }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-www
  labels:
    {{- include "portfolio.labels" . | nindent 4 }}
spec:
  redirectRegex:
    regex: ^https?://www\.(.+)
    replacement: https://${1}
    permanent: true
{{- end }}
