apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: portfolio
  labels:
    {{- include "portfolio.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "portfolio.selectorLabels" . | nindent 6 }}
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
      ports:
        - port: 8080
          protocol: TCP
  egress: []
