apiVersion: v1
kind: Service
metadata:
  name: portfolio
  labels:
    {{- include "portfolio.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "portfolio.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
